### ISSUE TITLE
CatWrt ToDo 适配进展

### ISSUE THREAD

**Issue by miaoermua** [miaoermua/CatWrt#1]
这里记录一下工作进度

- [ ] https://github.com/miaoermua/CatWrt/issues/12
- [ ] 修复 ARM 平台驱动问题
- [ ] 设备支持 树莓派 4b

未来工作

- [ ] 优化目录结构
- [ ] 尝试解决使用主路由拨号时 ZeroTier 高占用的问题
